# Generated by Django 6.0.3 on 2026-04-06 09:07

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveRecordManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("investment", "Investment"),
                            ("freelance", "Freelance"),
                            ("utilities", "Utilities"),
                            ("healthcare", "Healthcare"),
                            ("food", "Food"),
                            ("rent", "Rent"),
                            ("transport", "Transport"),
                            ("education", "Education"),
                            ("entertainment", "Entertainment"),
                            ("tax", "Tax"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
