# Generated by Django 6.0.3 on 2026-04-06 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(
                fields=["type", "date"], name="records_fin_type_8d7c97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialrecord",
            index=models.Index(
                fields=["category", "date"], name="records_fin_categor_801bd6_idx"
            ),
        ),
    ]
